name: Staging pipeline for Saleor_Project

on:
  push:
    branches: [ Staging ]
  pull_request:
    branches: [ Staging ]

jobs:
  compose:
    name: Compose Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Compose
        run: |
          docker compose up -d

      - name: Health Checks
        run: |
          sleep 30
          services=(saleor_project-api-1 saleor_project-dashboard-1 saleor_project-db-1 saleor_project-redis-1 saleor_project-jaeger-1 saleor_project-mailpit-1)
          for service in "${services[@]}"; do
            echo "Checking health of $service..."
            for i in {1..10}; do
              STATUS=$(docker inspect --format='{{json .State.Health.Status}}' $service 2>/dev/null | tr -d '"')
              if [ -z "$STATUS" ]; then
                echo "Service $service does not exist or health status is unavailable. Skipping..."
                break
              fi
              echo "$service health status: $STATUS"
              if [ "$STATUS" == "healthy" ]; then
                echo "$service is healthy!"
                break
              elif [ "$STATUS" == "unhealthy" ] || ["$STATUS" == "started" ]; then
                echo "$service failed health checks."
                exit 1
              fi
              sleep 5
            done
          done

      - name: Stop Docker Compose
        run: docker compose down

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
               
      - name: Build API Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor_project-api:staging ./saleor-api
      
      - name: Build Dashboard Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor_project-dashboard:staging ./saleor-dashboard
      
      - name: API Image Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/saleor_project-api:staging'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Dasbhoard Image Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/saleor_project-dashboard:staging'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
                
      - name: Push to Dockerhub
        run: |
          docker image push ${{ secrets.DOCKER_USERNAME }}/saleor_project-api:staging
          docker image push ${{ secrets.DOCKER_USERNAME }}/saleor_project-dashboard:staging


